"""Initial migration

Revision ID: dbc146a7a938
Revises: 
Create Date: 2026-04-09 00:47:17.496210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbc146a7a938'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.Column('scan_reset_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('resume_hash', sa.String(length=64), nullable=True),
    sa.Column('resume_storage_path', sa.String(), nullable=True),
    sa.Column('jd_text', sa.String(), nullable=False),
    sa.Column('gemini_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claude_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_score_gemini', sa.Integer(), nullable=True),
    sa.Column('match_score_claude', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('user_preferred_ai', sa.String(length=10), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_resume_hash'), 'scans', ['resume_hash'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_resume_hash'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
